name: nibble
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - atomicwrites=1.1.5
  - attrs=18.1.0
  - automat=0.7.0
  - autopep8=1.4
  - backcall=0.1.0
  - beautifulsoup4=4.6.3
  - bleach=2.1.4
  - blinker=1.4
  - boto3=1.9.4
  - botocore=1.12.4
  - bzip2=1.0.6
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - clangdev=6.0.1
  - cloudpickle=0.5.5
  - constantly=15.1.0
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - cssselect=1.0.3
  - cycler=0.10.0
  - cymem=1.31.2
  - cytoolz=0.9.0.1
  - dask-core=0.19.1
  - decorator=4.3.0
  - dill=0.2.8.2
  - docutils=0.14
  - entrypoints=0.2.3
  - flake8=3.5.0
  - freetype=2.9.1
  - funcy=1.10.3
  - future=0.16.0
  - html5lib=1.0.1
  - hyperlink=17.3.1
  - icu=58.2
  - idna=2.7
  - imageio=2.3.0
  - incremental=17.5.0
  - invoke=1.1.1
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.0
  - jedi=0.12.1
  - jinja2=2.10
  - jmespath=0.9.3
  - joblib=0.12.5
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - kiwisolver=1.0.1
  - libcxx=6.0.1
  - libffi=3.2.1
  - libiconv=1.15
  - libpng=1.6.35
  - libsodium=1.0.16
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvm-meta=6.0.1
  - llvmdev=6.0.1
  - lxml=4.2.5
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mccabe=0.6.1
  - mistune=0.8.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - msgpack-numpy=0.4.3.1
  - msgpack-python=0.5.6
  - murmurhash=0.28.0
  - nb_conda_kernels=2.1.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=2.1
  - nltk=3.2.5
  - notebook=5.6.0
  - numexpr=2.6.6
  - oauthlib=2.1.0
  - olefile=0.45.1
  - openblas=0.2.20
  - openmp=6.0.1
  - openssl=1.0.2p
  - pandas=0.23.4
  - pandoc=2.2.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - patsy=0.5.0
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=18.0
  - plac=0.9.6
  - pluggy=0.7.1
  - preshed=1.0.1
  - prometheus_client=0.3.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - py=1.5.4
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.1
  - pycodestyle=2.3.1
  - pycparser=2.18
  - pydispatcher=2.0.5
  - pydotplus=2.0.2
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pyhamcrest=1.9.0
  - pyjwt=1.6.4
  - pyldavis=2.1.2
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.6.0
  - pysocks=1.6.8
  - pytest=3.7.2
  - pytest-mock=1.10.0=py36_1000
  - pytest-runner=4.2
  - python=3.6.6
  - python-crfsuite=0.9.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=1.0.0
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.4.1
  - readline=7.0
  - regex=2017.11.09
  - requests=2.19.1
  - requests-oauthlib=1.0.0
  - s3transfer=0.1.13
  - scikit-image=0.14.0
  - scrapy=1.5.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - smart_open=1.6.0
  - spacy=2.0.12
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.3.1
  - thinc=6.10.3
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - tqdm=4.26.0
  - traitlets=4.3.2
  - twython=3.7.0
  - ujson=1.35
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.0
  - wrapt=1.10.11
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope.interface=4.5.0
  - anaconda=custom
  - blas=1.0
  - boto=2.49.0
  - bz2file=0.98
  - gensim=3.4.0
  - intel-openmp=2018.0.3
  - mkl=2018.0.3
  - numpy=1.15.1
  - numpy-base=1.15.1
  - parsel=1.5.0
  - queuelib=1.5.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - twisted=17.5.0
  - w3lib=1.19.0
  - wget=1.19.5
  - pip:
    - click==7.0
    - dask==0.19.1
    - ipython-sql==0.3.9
    - kaggle==1.4.7.1
    - msgpack==0.5.6
    - prettytable==0.7.2
    - python-slugify==1.2.6
    - sqlalchemy==1.2.11
    - sqlparse==0.2.4
    - unidecode==1.0.22
